SHELL := /bin/bash

.PHONY: bootstrap pull-models create-models run smoke lint test eval

bootstrap:
	python -m pip install --upgrade pip
	pip install -e .[dev]
	pre-commit install

pull-models:
	bash scripts/pull_models.sh

create-models:
	bash scripts/create_models.sh

run:
	bash scripts/start_server.sh

smoke:
	pytest -q tests/test_smoke_ollama.py -q

lint:
	bash scripts/lint.sh

test:
	bash scripts/test.sh

eval:
	bash scripts/run_evals.sh
