defaults:
  escalate_on: ["invalid_json", "schema_fail", "uncertainty_markers", "refusal_detected"]
task_map:
  bug_triage:   { initial: "devstral:24b",       chain: ["qwen3-coder:30b", "nemotron:70b"] }
  code_assist:  { initial: "qwen3-coder:30b",    chain: ["nemotron:70b"] }
  design_rfc:   { initial: "gemma3:27b-it-qat",  chain: ["nemotron:70b"] }
  extraction:   { initial: "devstral:24b",       chain: ["qwen3-coder:30b"] }
  creative:     { initial: "gemma3:27b-it-qat",  chain: [] }
  analytical:   { initial: "devstral:24b",       chain: ["qwen3:30b"] }
